Repository CyberCoyotes/2025-Reefscape, pull requests merged in 2025-04, with the labels that each got.

#274 Refactor drive commands
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/DriveCommands.java
  src/main/java/frc/robot/commands/DriveDistanceCommands.java
  src/main/java/frc/robot/commands/DriveForwardCommand.java
  src/main/java/frc/robot/commands/DriveUntilDistance.java
  src/main/java/frc/robot/commands/SlowMoDriveCommand.java
Labels: sub-drivetrain

#275 Choreo changes made at comp
  src/main/deploy/choreo/SB-B.traj
  src/main/deploy/choreo/ST-A.traj
  src/main/deploy/choreo/ST-ABlue.traj
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/auto/AutoRoutines.java
  src/main/java/frc/robot/commands/CommandGroups.java
  src/main/java/frc/robot/subsystems/wrist/WristConstants.java
Labels: mode-autonomous

#278 Add second effector motor to EffectorSubsystem and update control met…
  src/main/java/frc/robot/commands/CommandGroups.java
  src/main/java/frc/robot/commands/EndEffectorCommands.java
  src/main/java/frc/robot/subsystems/endEffector/EffectorSubsystem.java
Labels: sub-effector

#284 Separate end effector motors
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/commands/EndEffectorCommands.java
  src/main/java/frc/robot/subsystems/endEffector/EffectorConstants.java
  src/main/java/frc/robot/subsystems/endEffector/EffectorSubsystem.java
Labels: sub-effector

#286 Add auto intake routine with drive command sequence
  src/main/java/frc/robot/auto/AutoRoutines.java
  src/main/java/frc/robot/commands/CommandGroups.java
Labels: mode-autonomous

#287 AUTO CHANGES
  src/main/deploy/choreo/SB-A.traj
  src/main/java/frc/robot/auto/AutoRoutines.java
Labels: mode-autonomous
